[tool.poetry]
name = "TradingBot"
version = "1.2.0"
description = "Autonomous market trader based on custom strategies"
authors = ["Alberto Cardellini"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ilcardella/TradingBot"
documentation = "https://tradingbot.readthedocs.io/en/latest"
packages = [
    { include = "tradingbot" }
]
include = ["config/config.json"]

[tool.poetry.dependencies]
python = "^3.6.1"
alpha-vantage = "^2.2.0"
govuk-bank-holidays = "^0.8"
numpy = "^1.18.4"
pandas = "^1.0.5"
pytz = "^2020.1"
requests = "^2.23.0"
scipy = "^1.5.1"
yfinance = "^0.1.54"

[tool.poetry.dev-dependencies]
sphinx = "^3.1.1"
sphinx-rtd-theme = "^0.5.0"
requests-mock = "^1.8.0"
pytest = "^5.4.3"
black = {version = "^19.10b0", allow-prereleases = true}
flake8 = "^3.8.3"
isort = "^5.0.2"
mypy = "^0.782"

[tool.poetry.scripts]
trading_bot = 'tradingbot.__main__:main'

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output=3
include_trailing_comma="True"
force_grid_wrap=0
use_parentheses="True"
line_length=88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
